version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "02:17" # GitHub says 'High load times include the start of every hour'
      timezone: "Europe/Oslo"
    pull-request-branch-name:
      separator: "-"
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: "maven"
    directory: "/dhis-2"
    schedule:
      interval: "daily"
      time: "02:17" # GitHub says 'High load times include the start of every hour'
      timezone: "Europe/Oslo"
    open-pull-requests-limit: 5
    pull-request-branch-name:
      separator: "-"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "java"
      - "run-api-tests"
    ignore:
      - dependency-name: "org.hibernate:hibernate-core" # we cannot yet update to 5.6 or above due to https://github.com/vladmihalcea/hibernate-types#installation
        versions:
          - ">= 5.6"
      - dependency-name: "org.hibernate:hibernate-echache" # needs to stay in sync with hibernate-core, versions are kept in sync in pom via hibernate.version
        versions:
          - ">= 5.6"
      - dependency-name: "org.hibernate:hibernate-spatial" # needs to stay in sync with hibernate-core, versions are kept in sync in pom via hibernate.versions
        versions:
          - ">= 5.6"
      - dependency-name: "org.hibernate:hibernate-validator" # requires more work due to package changes https://hibernate.org/validator/documentation/migration-guide/#7-0-x
        versions:
          - ">= 7.0"
      - dependency-name: "com.fasterxml.jackson.datatype:jackson-datatype-hibernate5" # later versions have failing tests
        versions:
          - ">= 2.11.2"
      - dependency-name: "com.fasterxml.jackson.core:jackson-core" # later versions have failing tests
        versions:
          - ">= 2.13.0"
      - dependency-name: "com.fasterxml.jackson.core:jackson-annotations" # later versions have failing tests
        versions:
          - ">= 2.13.0"
      - dependency-name: "com.fasterxml.jackson.core:jackson-databind" # later versions have failing tests
        versions:
          - ">= 2.13.0"
      - dependency-name: "com.fasterxml.jackson.dataformat:jackson-dataformat-xml" # later versions have failing tests
        versions:
          - ">= 2.13.0"
      - dependency-name: "com.fasterxml.jackson.dataformat:jackson-dataformat-csv" # later versions have failing tests
        versions:
          - ">= 2.13.0"
      - dependency-name: "com.fasterxml.jackson.datatype:jackson-datatype-jdk8" # later versions have failing tests
        versions:
          - ">= 2.13.0"
      - dependency-name: "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" # later versions have failing tests
        versions:
          - ">= 2.13.0" 
      - dependency-name: "org.eclipse.jetty:*" # Jetty 11 moved some code to a different package, updated the Servlet version which requires more work
        versions:
          - ">= 11.0"
