version: '3'
services:
  redis:
    image: redis:5.0.5-alpine
    volumes:
    - ./config/redis/redis.conf:/usr/local/etc/redis.conf
    ports:
       - "6379"

  db:
    restart: always
    image: mdillon/postgis:10-alpine
    command: postgres -c max_locks_per_transaction=500 -c wal_level=logical -c max_wal_senders=3 -c max_replication_slots=20
    environment:
      POSTGRES_USER: dhis
      POSTGRES_DB: dhis2
      POSTGRES_PASSWORD: dhis

  web:
    image: "dhis2/core-dev:2.37.0-rc"
    volumes:
    - ./config/dhis2_home/dhis.conf:/DHIS2_home/dhis.conf
    environment:
      - WAIT_FOR_DB_CONTAINER=db:5432 -t 0
    depends_on:
    - db
    - redis
    scale: 1

  nginx:
    image: "jwilder/nginx-proxy:alpine"
    restart: always
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - db
      - web
      - redis
    ports:
      - "8080:80"

