name: Run api tests

on:
  pull_request: 
    types: [ labeled, synchronize ]
jobs:
  cleanup-runs:
   runs-on: ubuntu-latest
   steps:
   - uses: rokroskar/workflow-run-cleanup-action@master
     env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/master'"
     
  api-test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.pull_request.labels.*.name, 'skip-api-tests')"
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Set up environment
        run: |
          cd dhis-2
          docker-compose -f ./dhis-e2e-test/docker-compose.yml run --publish 5432:5432 -d db
          export DHIS2_HOME=./dhis-e2e-test/config/dhis2_home/local-db/
          bash ./run-api.sh

      - name: Run tests
        run: |
          cd dhis-2/dhis-e2e-test
          mvn test -Dinstance.url=http://localhost:9090/api -Dtest.cleanup=false -Duser.default.username=admin -Duser.default.password=district
