name: Run api tests

on:
  pull_request: 
    types: [ labeled, synchronize ]
concurrency:
    group: ${{ github.workflow}}-${{ github.ref }}
    cancel-in-progress: true
jobs:    
  api-test:
    env:
      CORE_IMAGE_NAME: "dhis2/core:local"
      TEST_IMAGE_NAME: "dhis2/tests:local"
    runs-on: ubuntu-latest
    if: "!contains(github.event.pull_request.labels.*.name, 'skip-api-tests')"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Build core image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          load: true
          tags: dhis2/core:local
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run tests
        run: |
          cd dhis-2/dhis-e2e-test
          IMAGE_NAME=$CORE_IMAGE_NAME docker-compose up -d
          docker build -t $TEST_IMAGE_NAME .
          IMAGE_NAME=$TEST_IMAGE_NAME docker-compose -f docker-compose.e2e.yml up --exit-code-from e2e-test

      - name: Upload logs
        if: failure()
        run: |
          cd dhis-2/dhis-e2e-test
          docker-compose logs web > ~/logs.txt

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: "tomcat_logs"
          path: '~/logs.txt'
